name: Changesets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  changesets:
    name: Version Packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create Versioning Pull Request
        id: changesets
        uses: changesets/action@v1.7.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          createGithubReleases: true
          version: npm run changeset version
          publish: npm run changeset tag
